### ISSUE TITLE
Comments Removed from Template Files

### ISSUE THREAD

**Issue by LoveAndCoding** [mentaljam/rollup-plugin-html2#15]
HTML comments seem to be removed from template files. From the looks of it, [when the files contents are sent to the parser](https://github.com/mentaljam/rollup-plugin-html2/blob/master/src/index.ts#L247), it doesn't set any options and the default configuration for `node-html-parser` is to [remove comments](https://github.com/taoqf/node-html-parser/blob/main/src/nodes/html.ts#L1150).

It'd be great to either have this not remove comments (since the minifier can be configured to do so anyway), or to allow passing options to the parser.

**Comment by mentaljam** [comment]
Fixed, thanks!
