### ISSUE TITLE
Modern and legacy js injection

### ISSUE THREAD

**Issue by stalniy** [mentaljam/rollup-plugin-html2#2]
I want to inject 2 js files, one for modern browsers `<script module src="...">` and another for legacy ones `<script nomodule src="...">`.

Is it possible to do it right now?

**Comment by mentaljam** [comment]
Hi,

I have added the `nomodule` option and also updated an example of how to generate an HTML file with both module and nomodule scripts. It looks like a quite ugly hack but I cannot come up with anything better now.

May be you have any ideas?

**Comment by mentaljam** [comment]
The [example](https://github.com/mentaljam/rollup-plugin-html2/blob/efb9eebb14ccfd91358d4967692be9a8d2778ca5/examples/config/nomodule.mjs) was updated
